outputfile = open("colorstate.txt", "w")
outputfile.write("0" + "\n")
outputfile.write(0 + "\n")
outputfile.write(0 + "\n")
outputfile.write(0 + "\n")
outputfile.write(0 + "\n")
outputfile.write("0" + "\n")